//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificados
    {
        public int Id { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public int num_certificado { get; set; }
        public int comerciantes_id { get; set; }
        public string codigo_verificacion { get; set; }
        public bool certificado_valido { get; set; }
    
        public virtual Comerciantes Comerciantes { get; set; }
    }
}
