//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComerciantesEntities : DbContext
    {
        public ComerciantesEntities()
            : base("name=ComerciantesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comerciantes> Comerciantes { get; set; }
        public virtual DbSet<Certificados> Certificados { get; set; }
        public virtual DbSet<Institucion> Institucion { get; set; }
        public virtual DbSet<Rectificaciones> Rectificaciones { get; set; }
        public virtual DbSet<Datos> Datos { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
        public virtual DbSet<Plantilla_Dato> Plantilla_Dato { get; set; }
        public virtual DbSet<Plantillas> Plantillas { get; set; }
    }
}
