//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int Id { get; set; }
        public System.DateTime fecha_generado { get; set; }
        public int dato_id { get; set; }
        public string ruta_archivo { get; set; }
        public string codigo_verificacion { get; set; }
        public bool valido { get; set; }
    
        public virtual Datos Datos { get; set; }
    }
}
