//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantillas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantillas()
        {
            this.Plantilla_Dato = new HashSet<Plantilla_Dato>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public bool nombres_plantilla { get; set; }
        public bool apellidos_plantilla { get; set; }
        public bool curso_plantilla { get; set; }
        public bool fecha_plantilla { get; set; }
        public bool opcional1_plantilla { get; set; }
        public bool opcional2_plantilla { get; set; }
        public bool opcional3_plantilla { get; set; }
        public bool opcional4_plantilla { get; set; }
        public string archivo_plantilla { get; set; }
        public bool plantilla_activa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantilla_Dato> Plantilla_Dato { get; set; }
    }
}
