//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rectificaciones
    {
        public int Id { get; set; }
        public bool rectificar_nom_ape { get; set; }
        public bool rectificar_cedula { get; set; }
        public int rectificar_inst_origen { get; set; }
        public int rectificar_inst_destino { get; set; }
        public int comerciantes_id { get; set; }
        public System.DateTime fecha_rectificar { get; set; }
        public int num_solicitud { get; set; }
        public bool solicitud_atendida { get; set; }
    
        public virtual Comerciantes Comerciantes { get; set; }
    }
}
